In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [4]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Eureka,US,2021-03-28 19:52:26,40.8021,-124.1637,52.0,93,90,6.87
1,1,Santa Ana,US,2021-03-28 19:51:44,33.7456,-117.8678,86.0,17,1,4.61
2,2,Nikolskoye,RU,2021-03-28 19:52:27,59.7035,30.7861,41.0,87,90,4.50
3,3,Busselton,AU,2021-03-28 19:52:27,-33.6500,115.3333,54.0,94,0,1.01
4,4,Tandahimba,TZ,2021-03-28 19:52:27,-10.7500,39.6333,71.8,93,93,1.81

In [7]:
# check the dataframe's type
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [8]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [21]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable. Use list comprehension to delete any max temps that are negative because you cannot
# weigh with a negative number
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], 
                                 dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Heatmap of % humidity
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
humidity = city_data_df["Humidity"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable. 
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Heatmap of % cloudiness
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
cloudiness = city_data_df["Cloudiness"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable. 
heat_layer = gmaps.heatmap_layer(locations, weights=cloudiness, 
                                 dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
# Heatmap of wind speed
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
wind_speed = city_data_df["Wind Speed"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable. 
heat_layer = gmaps.heatmap_layer(locations, weights=wind_speed, 
                                 dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [31]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 90
What is the maximum temperature you would like for your trip? 110

In [34]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp).dropna() & \
                                       (city_data_df["Max Temp"] >= min_temp).dropna()]
preferred_cities_df.tail(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
19,19,Paranaiba,BR,2021-03-28 19:52:33,-19.6772,-51.1908,95.56,22,3,4.16
70,70,Nouna,BF,2021-03-28 19:52:52,12.7333,-3.8667,90.19,10,0,7.92
233,233,San Miguel,SV,2021-03-28 19:53:59,13.4833,-88.1833,100.40,22,0,2.30
273,273,Manzanillo,CU,2021-03-28 19:54:14,20.3433,-77.1167,90.37,38,40,14.23
291,291,Puerto Madero,MX,2021-03-28 19:54:23,14.7208,-92.4215,93.20,52,40,14.97
335,335,Panaba,MX,2021-03-28 19:54:50,21.2833,-88.2667,97.81,27,0,13.44
403,403,Mandera,KE,2021-03-28 19:55:21,3.9366,41.8670,90.59,26,100,0.78
506,506,Carinhanha,BR,2021-03-28 19:55:55,-14.3047,-43.7650,93.25,21,100,4.12

In [35]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat      Lng Hotel Name
19       Paranaiba      BR     95.56 -19.6772 -51.1908
70           Nouna      BF     90.19  12.7333  -3.8667
233     San Miguel      SV    100.40  13.4833 -88.1833
273     Manzanillo      CU     90.37  20.3433 -77.1167
291  Puerto Madero      MX     93.20  14.7208 -92.4215
335         Panaba      MX     97.81  21.2833 -88.2667
403        Mandera      KE     90.59   3.9366  41.8670
506     Carinhanha      BR     93.25 -14.3047 -43.7650

In [50]:
base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": ""
    }

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
   # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

In [51]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
19,Paranaiba,BR,95.56,-19.6772,-51.1908,Villa Rica Park Hotel GMR
70,Nouna,BF,90.19,12.7333,-3.8667,Sabunyuma So
233,San Miguel,SV,100.40,13.4833,-88.1833,Hotel Tropico Inn San Miguel
273,Manzanillo,CU,90.37,20.3433,-77.1167,"HOSTAL ""THE YELLOW HOUSE"""
291,Puerto Madero,MX,93.20,14.7208,-92.4215,Hotel La Central
335,Panaba,MX,97.81,21.2833,-88.2667,Posada rosario
403,Mandera,KE,90.59,3.9366,41.8670,Kornesh Hotel and Lodging
506,Carinhanha,BR,93.25,-14.3047,-43.7650,Hotel Canoeiro

In [57]:
#add marker popups
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [58]:
# make hotel df heatmap for max temp
# Get the latitude and longitude.
locations = hotel_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp_pref = hotel_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable. Use list comprehension to delete any max temps that are negative because you cannot
# weigh with a negative number
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp_pref], 
                                 dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer and markers with popups.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))